// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/armagos2016.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CR_reg_cond_cpp
List CR_reg_cond_cpp(int n, int nchi, int T_obs, int K, int p, int q, int d1, int d2, int d, mat beta1, mat beta2, mat V, colvec tau, mat Z, cube Zi, mat F_mat, std::string dataset);
RcppExport SEXP armagos2016_CR_reg_cond_cpp(SEXP nSEXP, SEXP nchiSEXP, SEXP T_obsSEXP, SEXP KSEXP, SEXP pSEXP, SEXP qSEXP, SEXP d1SEXP, SEXP d2SEXP, SEXP dSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP VSEXP, SEXP tauSEXP, SEXP ZSEXP, SEXP ZiSEXP, SEXP F_matSEXP, SEXP datasetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nchi(nchiSEXP);
    Rcpp::traits::input_parameter< int >::type T_obs(T_obsSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< int >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< mat >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< mat >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< colvec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< cube >::type Zi(ZiSEXP);
    Rcpp::traits::input_parameter< mat >::type F_mat(F_matSEXP);
    Rcpp::traits::input_parameter< std::string >::type dataset(datasetSEXP);
    rcpp_result_gen = Rcpp::wrap(CR_reg_cond_cpp(n, nchi, T_obs, K, p, q, d1, d2, d, beta1, beta2, V, tau, Z, Zi, F_mat, dataset));
    return rcpp_result_gen;
END_RCPP
}
// CR_reg_cpp
List CR_reg_cpp(colvec a, mat b, mat V, mat Vxi, colvec tau, mat F_mat, int n, int nchi, int T_obs, int K, std::string dataset);
RcppExport SEXP armagos2016_CR_reg_cpp(SEXP aSEXP, SEXP bSEXP, SEXP VSEXP, SEXP VxiSEXP, SEXP tauSEXP, SEXP F_matSEXP, SEXP nSEXP, SEXP nchiSEXP, SEXP T_obsSEXP, SEXP KSEXP, SEXP datasetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< colvec >::type a(aSEXP);
    Rcpp::traits::input_parameter< mat >::type b(bSEXP);
    Rcpp::traits::input_parameter< mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< mat >::type Vxi(VxiSEXP);
    Rcpp::traits::input_parameter< colvec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< mat >::type F_mat(F_matSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nchi(nchiSEXP);
    Rcpp::traits::input_parameter< int >::type T_obs(T_obsSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< std::string >::type dataset(datasetSEXP);
    rcpp_result_gen = Rcpp::wrap(CR_reg_cpp(a, b, V, Vxi, tau, F_mat, n, nchi, T_obs, K, dataset));
    return rcpp_result_gen;
END_RCPP
}
// TSRegress_CN_V_cond_cpp
List TSRegress_CN_V_cond_cpp(mat R, colvec Rf, mat F_mat, mat Z, cube Zi);
RcppExport SEXP armagos2016_TSRegress_CN_V_cond_cpp(SEXP RSEXP, SEXP RfSEXP, SEXP F_matSEXP, SEXP ZSEXP, SEXP ZiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< colvec >::type Rf(RfSEXP);
    Rcpp::traits::input_parameter< mat >::type F_mat(F_matSEXP);
    Rcpp::traits::input_parameter< mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< cube >::type Zi(ZiSEXP);
    rcpp_result_gen = Rcpp::wrap(TSRegress_CN_V_cond_cpp(R, Rf, F_mat, Z, Zi));
    return rcpp_result_gen;
END_RCPP
}
// TSRegress_CN_V_cpp
List TSRegress_CN_V_cpp(mat R, colvec Rf, mat F_mat);
RcppExport SEXP armagos2016_TSRegress_CN_V_cpp(SEXP RSEXP, SEXP RfSEXP, SEXP F_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< colvec >::type Rf(RfSEXP);
    Rcpp::traits::input_parameter< mat >::type F_mat(F_matSEXP);
    rcpp_result_gen = Rcpp::wrap(TSRegress_CN_V_cpp(R, Rf, F_mat));
    return rcpp_result_gen;
END_RCPP
}
// UnbiasedEst_cond_cpp
colvec UnbiasedEst_cond_cpp(colvec nu, mat vecbeta3, mat V, int K, int p, int q, int n, int T_obs, colvec tau, int d1, int d2, int d);
RcppExport SEXP armagos2016_UnbiasedEst_cond_cpp(SEXP nuSEXP, SEXP vecbeta3SEXP, SEXP VSEXP, SEXP KSEXP, SEXP pSEXP, SEXP qSEXP, SEXP nSEXP, SEXP T_obsSEXP, SEXP tauSEXP, SEXP d1SEXP, SEXP d2SEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< colvec >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< mat >::type vecbeta3(vecbeta3SEXP);
    Rcpp::traits::input_parameter< mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type T_obs(T_obsSEXP);
    Rcpp::traits::input_parameter< colvec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< int >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(UnbiasedEst_cond_cpp(nu, vecbeta3, V, K, p, q, n, T_obs, tau, d1, d2, d));
    return rcpp_result_gen;
END_RCPP
}
// UnbiasedEst_cpp
colvec UnbiasedEst_cpp(colvec nu, mat b, mat V, mat Vxi, colvec tau, int n, int T_obs, int K);
RcppExport SEXP armagos2016_UnbiasedEst_cpp(SEXP nuSEXP, SEXP bSEXP, SEXP VSEXP, SEXP VxiSEXP, SEXP tauSEXP, SEXP nSEXP, SEXP T_obsSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< colvec >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< mat >::type b(bSEXP);
    Rcpp::traits::input_parameter< mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< mat >::type Vxi(VxiSEXP);
    Rcpp::traits::input_parameter< colvec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type T_obs(T_obsSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(UnbiasedEst_cpp(nu, b, V, Vxi, tau, n, T_obs, K));
    return rcpp_result_gen;
END_RCPP
}
