# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CR_reg_cond_cpp <- function(n, nchi, T_obs, K, p, q, d1, d2, d, beta1, beta2, V, tau, Z, Zi, F_mat, dataset) {
    .Call('armagos2016_CR_reg_cond_cpp', PACKAGE = 'armagos2016', n, nchi, T_obs, K, p, q, d1, d2, d, beta1, beta2, V, tau, Z, Zi, F_mat, dataset)
}

CR_reg_cpp <- function(a, b, V, Vxi, tau, F_mat, n, nchi, T_obs, K, dataset) {
    .Call('armagos2016_CR_reg_cpp', PACKAGE = 'armagos2016', a, b, V, Vxi, tau, F_mat, n, nchi, T_obs, K, dataset)
}

TSRegress_CN_V_cond_cpp <- function(R, Rf, F_mat, Z, Zi) {
    .Call('armagos2016_TSRegress_CN_V_cond_cpp', PACKAGE = 'armagos2016', R, Rf, F_mat, Z, Zi)
}

TSRegress_CN_V_cpp <- function(R, Rf, F_mat) {
    .Call('armagos2016_TSRegress_CN_V_cpp', PACKAGE = 'armagos2016', R, Rf, F_mat)
}

UnbiasedEst_cond_cpp <- function(nu, vecbeta3, V, K, p, q, n, T_obs, tau, d1, d2, d) {
    .Call('armagos2016_UnbiasedEst_cond_cpp', PACKAGE = 'armagos2016', nu, vecbeta3, V, K, p, q, n, T_obs, tau, d1, d2, d)
}

UnbiasedEst_cpp <- function(nu, b, V, Vxi, tau, n, T_obs, K) {
    .Call('armagos2016_UnbiasedEst_cpp', PACKAGE = 'armagos2016', nu, b, V, Vxi, tau, n, T_obs, K)
}

